spring:
    main:
      allow-bean-definition-overriding: true
    config:
      import: "optional:configserver:${CLOUD_CONFIG_IMPORT_URL}"
    cloud:
      config:
        name: banner
        profile: ${BANNER_PROFILE}

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
          
management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh
      base-path: /
      path-mapping:
        health: /